#ifndef QPATELSOLVERS_H
#define QPATELSOLVERS_H
namespace gcf
{
enum GPATEL_SOLVERS
{
    GPATEL_LINE_EQ,
    GPATEL_PARABOLE_EQ,
    GPATEL_CIRCLE_EQ,
    GPATEL_QUADRATIC_EQ
};
}
#endif // QPATELSOLVERS_H
